import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, unlinkSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { getConfigDir } from "../config";
import { resolveAutoContext, type AutoContextMode } from "../claude/context-windows";
import { PROXY_MARKER, defaultAuthDetectDeps, detectClaudeAuth, isProxyMarker, ownAdmissionTokens } from "../claude/auth-detect";
import { resolveClaudeAuthMode } from "../claude/auth-mode";
import type { CodexCommanderConfig } from "../types";
import { recordOwnedConfigPath } from "../lib/config-ownership";

/**
 * Does the CodexCommander dummy marker belong in the system environment?
 *
 * Keyed on the SAME resolver `ccx claude` uses, so an auto config with no Claude auth
 * also reaches plain `claude` launches — before this, auto-absent users got nothing
 * from auto-connect and the feature looked broken for exactly the people it helps
 * (implementation contract).
 *
 * NOTE this is a SNAPSHOT: the file only changes when this runs (proxy start, `ccx
 * ensure`, or a settings save). `ccx claude` re-resolves live on every launch.
 */
function systemEnvMarkerMode(config: CodexCommanderConfig): "proxy" | "subscription" {
  return resolveClaudeAuthMode(config, detectClaudeAuth(defaultAuthDetectDeps(process.env, ownAdmissionTokens(config)))).markerMode;
}

// ---------------------------------------------------------------------------
// Shell-hook env file: written on inject, sourced by the shell hook in .zshrc.
// This works for ALL new shells immediately, unlike launchctl setenv which only
// reaches processes launched directly by launchd (not Terminal.app children).
// ---------------------------------------------------------------------------

export function getShellEnvFilePath(): string {
  return join(getConfigDir(), "claude-env.sh");
}

function shellValue(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function writeShellEnvFile(port: number, config: CodexCommanderConfig, modelEnv: Record<string, string> = {}, auto?: AutoContextMode): void {
  const lines = [
    `# Generated by CodexCommander — do not edit manually`,
    `export ANTHROPIC_BASE_URL=${shellValue(`http://127.0.0.1:${port}`)}`,
    `export CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY=${shellValue("1")}`,
  ];
  // New lever keys are CONDITIONAL exports (audit 139 R2#1): a value the user already
  // exported in their shell wins even though launchctl knows nothing about it.
  const conditional = (name: string, value: string) =>
    `[ -z "\${${name}+x}" ] && export ${name}=${shellValue(value)}`;
  if (config.apiKeys?.length) {
    lines.push(`export ANTHROPIC_AUTH_TOKEN=${shellValue(config.apiKeys[0].key)}`);
  } else if (systemEnvMarkerMode(config) === "proxy") {
    lines.push(conditional("ANTHROPIC_AUTH_TOKEN", PROXY_MARKER));
  }
  // Helper-model slots with [1m] applied.
  for (const [name, value] of Object.entries(modelEnv)) {
    lines.push(conditional(name, value));
  }
  // Auto-context (implementation contract 020): same contract as `ccx claude` / launchctl.
  const autoShell = auto ?? resolveAutoContext(config.claudeCode);
  if (autoShell.enabled) lines.push(conditional("CLAUDE_CODE_AUTO_COMPACT_WINDOW", String(autoShell.compactWindow)));
  const shellEnvPath = getShellEnvFilePath();
  recordOwnedConfigPath(getConfigDir(), shellEnvPath);
  mkdirSync(getConfigDir(), { recursive: true, mode: 0o700 });
  writeFileSync(shellEnvPath, lines.join("\n") + "\n", { encoding: "utf8", mode: 0o600 });
}

function removeShellEnvFile(): void {
  try { unlinkSync(getShellEnvFilePath()); } catch { /* already gone */ }
}

// ---------------------------------------------------------------------------
// .zshrc hook auto-install: adds a one-liner that sources claude-env.sh.
// Idempotent — skips if the hook line already exists.
// ---------------------------------------------------------------------------

const SHELL_HOOK_MARKER = "# CodexCommander claude-env hook";

function shellHookBlock(): string {
  const envFile = shellValue(getShellEnvFilePath());
  return `${SHELL_HOOK_MARKER}\n[ -f ${envFile} ] && . ${envFile}`;
}

function stripManagedShellHooks(content: string): string {
  const lines = content.split("\n");
  const kept: string[] = [];
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    if (line !== SHELL_HOOK_MARKER) {
      kept.push(line);
      continue;
    }
    if (lines[index + 1]?.includes("claude-env.sh")) index += 1;
  }
  return kept.join("\n");
}

export function installShellHook(): { installed: boolean; reason?: string } {
  if (process.platform !== "darwin") return { installed: false, reason: "not macOS" };
  const home = process.env.HOME;
  if (!home) return { installed: false, reason: "no HOME" };
  const zshrcPath = join(home, ".zshrc");
  try {
    let content = "";
    try { content = readFileSync(zshrcPath, "utf8"); } catch { /* file doesn't exist yet */ }
    const hook = shellHookBlock();
    if (content.includes(hook)) return { installed: false, reason: "already installed" };
    const cleaned = stripManagedShellHooks(content).replace(/\n*$/, "");
    writeFileSync(zshrcPath, `${cleaned}\n${hook}\n`, { encoding: "utf8", mode: 0o644 });
    return { installed: true };
  } catch (err) {
    return { installed: false, reason: `write failed: ${err instanceof Error ? err.message : String(err)}` };
  }
}

export function uninstallShellHook(): { removed: boolean; reason?: string } {
  if (process.platform !== "darwin") return { removed: false, reason: "not macOS" };
  const home = process.env.HOME;
  if (!home) return { removed: false, reason: "no HOME" };
  const zshrcPath = join(home, ".zshrc");
  try {
    const content = readFileSync(zshrcPath, "utf8");
    if (!content.includes(SHELL_HOOK_MARKER)) {
      return { removed: false, reason: "not installed" };
    }
    // Remove the hook block (marker line + source line + surrounding newlines)
    const cleaned = stripManagedShellHooks(content);
    writeFileSync(zshrcPath, cleaned, { encoding: "utf8", mode: 0o644 });
    return { removed: true };
  } catch {
    return { removed: false, reason: "read/write failed" };
  }
}

const SYSTEM_ENV_NAMES = [
  "ANTHROPIC_BASE_URL",
  "CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY",
  "ANTHROPIC_AUTH_TOKEN",
] as const;

const MANAGED_SYSTEM_ENV_NAMES = new Set<string>([
  ...SYSTEM_ENV_NAMES,
  "ANTHROPIC_DEFAULT_HAIKU_MODEL",
  "ANTHROPIC_SMALL_FAST_MODEL",
  "CLAUDE_CODE_AUTO_COMPACT_WINDOW",
]);

interface SystemEnvTracking {
  schemaVersion: 1;
  pid: number;
  port: number;
  injectedAt: string;
  /** Keys that were actually set by injection (revert only unsets these). */
  injectedKeys: string[];
}

type SystemEnvResult = { injected: boolean; reason?: string };
type RevertResult = { reverted: boolean; reason?: string };
type CleanupResult = { cleaned: boolean; reason?: string };

export function getSystemEnvTrackingPath(): string {
  return join(getConfigDir(), "system-env-port");
}

export function launchctlGetenv(name: string): string | undefined {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return undefined;
  try {
    const value = execFileSync("/bin/launchctl", ["getenv", name], { encoding: "utf8" }).trim();
    return value || undefined;
  } catch {
    return undefined;
  }
}

function readTracking(): SystemEnvTracking | undefined {
  try {
    const parsed = JSON.parse(readFileSync(getSystemEnvTrackingPath(), "utf8")) as unknown;
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return undefined;
    const tracking = parsed as Record<string, unknown>;
    const exactKeys = ["schemaVersion", "pid", "port", "injectedAt", "injectedKeys"];
    if (Object.keys(tracking).length !== exactKeys.length || exactKeys.some(key => !Object.hasOwn(tracking, key))) {
      return undefined;
    }
    if (tracking.schemaVersion !== 1
      || !Number.isSafeInteger(tracking.pid)
      || Number(tracking.pid) <= 0
      || !Number.isInteger(tracking.port)
      || Number(tracking.port) <= 0
      || Number(tracking.port) > 65535
      || typeof tracking.injectedAt !== "string"
      || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(tracking.injectedAt)
      || !Array.isArray(tracking.injectedKeys)
      || tracking.injectedKeys.some(name => typeof name !== "string" || !MANAGED_SYSTEM_ENV_NAMES.has(name))
      || new Set(tracking.injectedKeys).size !== tracking.injectedKeys.length) {
      return undefined;
    }
    return tracking as unknown as SystemEnvTracking;
  } catch {
    return undefined;
  }
}

function setLaunchctlEnv(name: string, value: string): void {
  execFileSync("/bin/launchctl", ["setenv", name, value]);
}

function unsetLaunchctlEnv(name: string): void {
  execFileSync("/bin/launchctl", ["unsetenv", name]);
}

function ownedBaseUrl(port: number): string {
  return `http://127.0.0.1:${port}`;
}

function writeTracking(port: number, injectedKeys: string[]): void {
  recordOwnedConfigPath(getConfigDir(), getSystemEnvTrackingPath());
  mkdirSync(getConfigDir(), { recursive: true, mode: 0o700 });
  writeFileSync(getSystemEnvTrackingPath(), JSON.stringify({
    schemaVersion: 1,
    pid: process.pid,
    port,
    injectedAt: new Date().toISOString(),
    injectedKeys,
  }), { encoding: "utf8", mode: 0o600 });
}

function rollbackInjectedKeys(port: number, injectedKeys: string[]): void {
  const rollbackFailed: string[] = [];
  for (const name of [...injectedKeys].reverse()) {
    try {
      unsetLaunchctlEnv(name);
    } catch {
      rollbackFailed.unshift(name);
    }
  }

  if (rollbackFailed.length > 0) {
    writeTracking(port, rollbackFailed);
    return;
  }

  try { unlinkSync(getSystemEnvTrackingPath()); } catch { /* already gone */ }
}

/**
 * In-process effective helper-model env ([1m] applied) under the shared
 * 3s bound (audit R4#3). Returns {} on timeout/failure so injection degrades safely.
 */
async function computeEffectiveModelEnv(config: CodexCommanderConfig, auto?: AutoContextMode): Promise<{ modelEnv: Record<string, string>; windows: Record<string, number> }> {
  const { boundedContextWindows, buildClaudeContextWindows, effectiveModelEnv } = await import("../claude/context-windows");
  const windows = await boundedContextWindows(async () => {
    const { gatherRoutedModels, visibleNativeSlugs } = await import("../codex/catalog");
    try {
      return buildClaudeContextWindows([...visibleNativeSlugs(config)], await gatherRoutedModels(config));
    } catch (error) {
      if (error && typeof error === "object" && (error as { code?: unknown }).code === "catalog_busy") {
        return buildClaudeContextWindows([...visibleNativeSlugs(config)], []);
      }
      throw error;
    }
  });
  return { modelEnv: effectiveModelEnv(config.claudeCode, windows ?? {}, auto), windows: windows ?? {} };
}

export async function injectSystemEnv(port: number, config: CodexCommanderConfig): Promise<SystemEnvResult> {
  if (process.platform !== "darwin") return { injected: false, reason: "not macOS" };
  if (config.claudeCode?.enabled === false) return { injected: false, reason: "claude disabled" };

  // Default OFF — only inject when explicitly enabled by the user.
  if (config.claudeCode?.systemEnv !== true) return { injected: false, reason: "systemEnv disabled" };

  await cleanStaleSystemEnv();

  const currentBaseUrl = launchctlGetenv("ANTHROPIC_BASE_URL");
  if (currentBaseUrl && !/^http:\/\/127\.0\.0\.1:\d+$/.test(currentBaseUrl)) {
    return { injected: false, reason: "user has custom ANTHROPIC_BASE_URL" };
  }
  // After stale cleanup, if a tracking file still exists with a DIFFERENT port,
  // another live instance owns the env — don't overwrite it.
  const existingTracking = readTracking();
  if (existingTracking && existingTracking.port !== port) {
    return { injected: false, reason: `another instance owns env (port ${existingTracking.port})` };
  }

  const injectedKeys: string[] = existingTracking
    ? [...existingTracking.injectedKeys]
    : [];
  const inject = (name: string, value: string) => {
    setLaunchctlEnv(name, value);
    if (!injectedKeys.includes(name)) injectedKeys.push(name);
    writeTracking(port, injectedKeys);
  };

  try {
    inject("ANTHROPIC_BASE_URL", ownedBaseUrl(port));
    inject("CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY", "1");
    if (config.apiKeys?.length) {
      inject("ANTHROPIC_AUTH_TOKEN", config.apiKeys[0].key);
    } else if (systemEnvMarkerMode(config) === "proxy" && launchctlGetenv("ANTHROPIC_AUTH_TOKEN") === undefined) {
      inject("ANTHROPIC_AUTH_TOKEN", PROXY_MARKER);
    } else if (systemEnvMarkerMode(config) !== "proxy"
      && injectedKeys.includes("ANTHROPIC_AUTH_TOKEN")
      && isProxyMarker(launchctlGetenv("ANTHROPIC_AUTH_TOKEN"))) {
      // Subscription switch-back (implementation contract): remove ONLY
      // the CodexCommander-owned dummy token so a launchd-started Claude regains its own
      // claude.ai OAuth. User-set tokens (not tracked in injectedKeys, or carrying a
      // different value) are never touched.
      unsetLaunchctlEnv("ANTHROPIC_AUTH_TOKEN");
      const dummyIdx = injectedKeys.indexOf("ANTHROPIC_AUTH_TOKEN");
      if (dummyIdx >= 0) injectedKeys.splice(dummyIdx, 1);
      writeTracking(port, injectedKeys);
    }
    // User-wins lever keys: skip any key the user already set in the
    // launchd domain, and track ONLY the keys we actually injected so revert cannot
    // delete a pre-existing user value (audit 139 #3).
    const injectLever = (name: string, value: string) => {
      if (launchctlGetenv(name) !== undefined) return;
      inject(name, value);
    };
    // Helper-model slots with [1m] auto-marking: in-process context-window
    // computation under the same 3s bound. On timeout the slots are not marked.
    // Auto-context: a user-owned launchd value drives the marking predicate so the
    // marker and threshold never separate (audit 021 #2); injectLever's user-wins
    // check below keeps that value untouched.
    const userAutoCompact = launchctlGetenv("CLAUDE_CODE_AUTO_COMPACT_WINDOW");
    const auto = resolveAutoContext(config.claudeCode, userAutoCompact);
    const { modelEnv, windows } = await computeEffectiveModelEnv(config, auto);
    for (const [name, value] of Object.entries(modelEnv)) {
      injectLever(name, value);
    }
    // Auto-context (implementation contract 020): user-wins lever.
    if (auto.enabled) injectLever("CLAUDE_CODE_AUTO_COMPACT_WINDOW", String(auto.compactWindow));

    // Shell-hook env file: works for new shells in already-running Terminal.app.
    writeShellEnvFile(port, config, modelEnv, auto);
    // Install the shell hook only after the user explicitly enables systemEnv and
    // injection succeeds. Startup must not mutate .zshrc while this feature is off.
    installShellHook();

    // Gateway-model cache pre-write (implementation contract): plain `claude` sessions read the
    // picker list from ~/.claude/cache/gateway-models.json and cannot refresh it
    // without a token — keep it in sync with this proxy's /v1/models. Best-effort.
    try {
      const { refreshGatewayModelCacheFromProxy } = await import("../claude/gateway-cache");
      await refreshGatewayModelCacheFromProxy(port);
    } catch { /* best-effort */ }

    // Roster agent definitions (implementation contract): same launch-time sync for plain `claude`.
    // Reuses the window map computed above (audit 071 #5 — no second acquisition).
    try {
      const { injectClaudeAgentDefs } = await import("../claude/agents-inject");
      injectClaudeAgentDefs(config, windows);
    } catch { /* best-effort */ }

    writeTracking(port, injectedKeys);
  } catch (error) {
    rollbackInjectedKeys(port, injectedKeys);
    removeShellEnvFile();
    console.error("Failed to inject system environment; rolled back launchctl changes:", error);
    throw error;
  }

  return { injected: true };
}

export async function applySystemEnvToggle(config: CodexCommanderConfig, port: number): Promise<SystemEnvResult | RevertResult> {
  if (config.claudeCode?.systemEnv === true) return injectSystemEnv(port, config);
  return revertSystemEnv();
}

export function revertSystemEnv(): RevertResult {
  if (process.platform !== "darwin") return { reverted: false, reason: "not macOS" };

  const tracking = readTracking();
  if (!tracking) return { reverted: false, reason: "no tracking file" };

  try {
    const tracksBaseUrl = tracking.injectedKeys.includes("ANTHROPIC_BASE_URL");
    if (tracksBaseUrl && launchctlGetenv("ANTHROPIC_BASE_URL") !== ownedBaseUrl(tracking.port)) {
      return { reverted: false, reason: "ownership mismatch" };
    }

    // Only unset keys that were actually injected (preserves pre-existing user tokens).
    for (const name of tracking.injectedKeys) {
      try {
        unsetLaunchctlEnv(name);
      } catch {
        // Continue removing the remaining variables during shutdown.
      }
    }
    removeShellEnvFile();
    try {
      unlinkSync(getSystemEnvTrackingPath());
    } catch {
      // The environment was reverted even if the tracking file disappeared concurrently.
    }
    return { reverted: true };
  } catch {
    return { reverted: false, reason: "revert failed" };
  }
}

export async function cleanStaleSystemEnv(): Promise<CleanupResult> {
  const tracking = readTracking();
  if (!tracking) return { cleaned: false, reason: "no tracking file" };

  try {
    const response = await fetch(`${ownedBaseUrl(tracking.port)}/healthz`, {
      signal: AbortSignal.timeout(1_000),
    });
    if (response.ok) return { cleaned: false, reason: "proxy still alive" };
  } catch {
    // A failed or timed-out health check means the tracked proxy is stale.
  }

  const reverted = revertSystemEnv();
  if (!reverted.reverted) return { cleaned: false, reason: reverted.reason };
  return { cleaned: true };
}
