/** Typed CodexCommander identity; see `identity.mjs` for the shared source. */
import {
  ADMIN_AUTH_REQUIRED_MESSAGE,
  ADMIN_KEY_PREFIX,
  API_KEY_HEADER,
  ARTIFACT_HTTP_PREFIX,
  ATTESTATION_CHALLENGE_HEADER,
  ATTESTATION_PROOF_HEADER,
  ATTESTATION_METADATA_PROOF_HEADER,
  AUTH_REQUIRED_MESSAGE,
  BRAND_DISPLAY,
  CLI_LONG,
  CLI_SHORT,
  CSRF_HEADER,
  DATA_KEY_PREFIX,
  GUI_ORIGIN_HEADER,
  GUI_LAUNCH_EXCHANGE_PATH,
  GUI_LAUNCH_TICKET_PATH,
  GUI_LAUNCH_TICKET_PREFIX,
  GUI_SESSION_PREFIX,
  HEALTH_SERVICE_ID,
  HOME_ENV,
  NPM_PACKAGE,
  OWNER_FILE,
  PACKAGE_SLUG,
  PROVIDER_ID,
  REPOSITORY_URL,
  SERVICE_LABEL,
  SERVICE_TASK,
  STATE_DIR_NAME,
  UNINSTALL_MANIFEST,
  WINSW_SERVICE_ID,
  readEnv,
} from "./identity.mjs";

export {
  ADMIN_AUTH_REQUIRED_MESSAGE,
  ADMIN_KEY_PREFIX,
  API_KEY_HEADER,
  ARTIFACT_HTTP_PREFIX,
  ATTESTATION_CHALLENGE_HEADER,
  ATTESTATION_PROOF_HEADER,
  ATTESTATION_METADATA_PROOF_HEADER,
  AUTH_REQUIRED_MESSAGE,
  BRAND_DISPLAY,
  CLI_LONG,
  CLI_SHORT,
  CSRF_HEADER,
  DATA_KEY_PREFIX,
  GUI_ORIGIN_HEADER,
  GUI_LAUNCH_EXCHANGE_PATH,
  GUI_LAUNCH_TICKET_PATH,
  GUI_LAUNCH_TICKET_PREFIX,
  GUI_SESSION_PREFIX,
  HEALTH_SERVICE_ID,
  HOME_ENV,
  NPM_PACKAGE,
  OWNER_FILE,
  PACKAGE_SLUG,
  PROVIDER_ID,
  REPOSITORY_URL,
  SERVICE_LABEL,
  SERVICE_TASK,
  STATE_DIR_NAME,
  UNINSTALL_MANIFEST,
  WINSW_SERVICE_ID,
  readEnv,
} from "./identity.mjs";

export function isOwnedProviderId(provider: string | undefined | null): boolean {
  return provider === PROVIDER_ID;
}

export function isOwnedHealthService(service: unknown): boolean {
  return service === HEALTH_SERVICE_ID;
}

export const ADMIN_KEY_PATTERN = new RegExp(`^${ADMIN_KEY_PREFIX}[A-Za-z0-9_-]{43}$`);
